### ISSUE TITLE
Update old descriptors to the new format

### ISSUE THREAD

**Issue by lconceicao** [sonata-nfv/son-examples#94]
Example service descriptors are outdated. They should be updated to the new connection points naming conventions, following the rules described in:

https://github.com/sonata-nfv/son-cli/issues/222

**Comment by mpeuster** [comment]
@lconceicao You are right!

The script that packs the services in Jenkins is this one: https://github.com/sonata-nfv/son-examples/blob/master/service-projects/pack.sh

@lconceicao Can you give me an example how to kick-off the right validation in there? Is it done automatically during packaging? I guess so! But then the job shouldn't run through, right?

Currently we see ` INFO ... syntax: True, integrity: False, topology: False`

Which of these validations tests the CP change? Do we need to set other versions in the `project.yml` or descriptors?

I don't think we can validate the topologies of each service, because the emulator examples sometimes contain very specific stuff, e.g., there should be not-connected CPs and stuff like this.

We also need to check against the emulator's dummy GK manually before closing this issue. (I'll do this once it runs through the validation).

**Comment by mpeuster** [comment]
@lconceicao  can you have a look at #95 this should capture all the changes required, right?

**Comment by lconceicao** [comment]
Regarding you previous comment, the son-package tool is only validating the services and function syntactically, which means that doesn't perform any integrity or topology validations. The new CP naming rules are validated in integrity, that's why the packaging is running with success.

Regarding #95, the VNFDs are incorrect. I'll detail in the PR comments.

**Comment by mpeuster** [comment]
Ha great! I guess I found everything I need. Added the validation to the pack.sh. So the Jenkins job which is running now should fail. I fix all the descriptors then :-)

**Comment by mpeuster** [comment]
Validation is active, descriptors are all fixed.
@stevenvanrossem can you check if everything still works with your example services before we close this issue?
